// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Bandeau RGPG', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Bandeau RGPG', async function() {
    await driver.get("https://amap.easylinux.lan/")
    assert(await driver.findElement(By.linkText("Accepter")).getText() == "Accepter")
    await driver.findElement(By.id("cookieConsent")).click()
    assert(await driver.findElement(By.linkText("Plus d\'informations")).getText() == "Plus d\\\'informations")
    await driver.findElement(By.linkText("Accepter")).click()
    await driver.findElement(By.linkText("De quoi s\'agit-il ?")).click()
    await driver.findElement(By.css("article > h2:nth-child(1)")).click()
    assert(await driver.findElement(By.css("article > h2:nth-child(1)")).getText() == "C\\\'est Quoi une AMAP ?")
    await driver.findElement(By.linkText("Nous rejoindre")).click()
    await driver.findElement(By.css("article > h2:nth-child(1)")).click()
    assert(await driver.findElement(By.css("article > h2:nth-child(1)")).getText() == "Comment nous rejoindre ?")
    await driver.findElement(By.linkText("Nos producteurs")).click()
    await driver.findElement(By.css("td > h2")).click()
    assert(await driver.findElement(By.css("td > h2")).getText() == "Nos producteurs et leurs contrats")
    await driver.findElement(By.linkText("Contacts")).click()
    await driver.findElement(By.css("article > h2:nth-child(1)")).click()
    assert(await driver.findElement(By.css("article > h2:nth-child(1)")).getText() == "Liste des référents")
  })
})
