// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Public', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Public', async function() {
    // Test name: Public
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("https://amap.easylinux.lan/")
    // 2 | setWindowSize | 1705x866 | 
    await driver.manage().window().setRect(1705, 866)
    // 3 | click | linkText=Accepter | 
    await driver.findElement(By.linkText("Accepter")).click()
    // 4 | click | linkText=Accueil | 
    await driver.findElement(By.linkText("Accueil")).click()
    // 5 | click | linkText=De quoi s'agit-il ? | 
    await driver.findElement(By.linkText("De quoi s\'agit-il ?")).click()
    // 6 | click | linkText=Nous rejoindre | 
    await driver.findElement(By.linkText("Nous rejoindre")).click()
    // 7 | click | linkText=Nos producteurs | 
    await driver.findElement(By.linkText("Nos producteurs")).click()
    // 8 | click | linkText=Contacts | 
    await driver.findElement(By.linkText("Contacts")).click()
    // 9 | click | css=h2 > a | 
    await driver.findElement(By.css("h2 > a")).click()
  })
})
