#!/bin/bash

cd /home/snoel/Documents/Projets/Amap-LesGumes/Tools

echo "Copie des fichiers"
rsync -rltv --exclude templates_c/*  --exclude _Backup/* --delete ../www/* root@Scaleway:/Data/Apps/LesGumes/dev

